### ISSUE TITLE
[Versions] Detail Endpoint Improvements 

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#391]
* The version detail endpoint for documents currently only contains the filename but not the other attributes like creation date, mime type, filesize etc. Why?
![image](https://github.com/user-attachments/assets/fb4ebec3-e73c-47ac-b930-b50f29510b06)

* Would it be possible to add the asset type of the version to the endpoint (so image, document etc.)?

**Comment by lukmzig** [comment]
> * The version detail endpoint for documents currently only contains the filename but not the other attributes like creation date, mime type, filesize etc. Why?

@markus-moser because it was not required? If you get the document detail in the classic UI you get the either a preview like for PDF or If the type is unknown (or defined as unknown e.g. csv) then you get default twig view with the link to download the asset version ... therefore the other attributes are not necessary

we have other endpoints for that:
- /studio/api/versions/{id}/pdf/stream
- /studio/api/versions/{id}/asset/download

> Would it be possible to add the asset type of the version to the endpoint (so image, document etc.)?

Yes, we can add the type to the endpoint :+1:

**Comment by markus-moser** [comment]
@lukmzig Ok, but we get creation type, mime type, filesize, asset metadata for images and in Pimcore there is no fundamental difference between those types in that aspect. So could you please add those attributes for the other asset types too (except folders because there we do not have versioning)? The version detail view should look the same for all types in Pimcore studio - yes there is a difference to the classic bundle, you're right!

Thanks a lot 👍

**Comment by lukmzig** [comment]
@markus-moser the endpoint should be now updated to deliver consistent data for all asset versions. I also added an asset type to the response.

**Comment by markus-moser** [comment]
@lukmzig Works like a charm - thx a lot!
