### ISSUE TITLE
New endpoint for `unlock-propagate`

### ISSUE THREAD

**Issue by Corepex** [pimcore/studio-backend-bundle#509]
### What

We need an endpoint to trigger the `unlockPropagate` method in the DAO ([asset](https://github.com/pimcore/pimcore/blob/56f8f152e5f0cead1f003b93d814e26279335505/models/Asset/Dao.php#L435), [document](https://github.com/pimcore/pimcore/blob/56f8f152e5f0cead1f003b93d814e26279335505/models/Document/Dao.php#L471), [dataObject](https://github.com/pimcore/pimcore/blob/56f8f152e5f0cead1f003b93d814e26279335505/models/DataObject/AbstractObject/Dao.php#L446))

Also see: https://github.com/pimcore/pimcore/blob/56f8f152e5f0cead1f003b93d814e26279335505/models/Asset/Dao.php#L438

### Some background info

When implementing the lock/unlock feature we can solve neatly everything with the `PATCH` endpoint but the `unlockPropagate` has a own endpoint - even in the legacy admin bundle. see: https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/src/Controller/Admin/ElementController.php#L440

**Comment by lukmzig** [comment]
@Corepex for the consistency we decided to add a new value to the updater/patcher instead of the new endpoint

you can pass these values to the `locked` fields:
- 'self' - locks only the element
- null - unlocks only the current element
- 'propagate' - lock and propagate to children
- 'unlockPropagate' . unlock and propagate to children

**Comment by Corepex** [comment]
@lukmzig thanks. IMHO is that the best solution. Much cleaner than a new endpoint 👍
