### ISSUE TITLE
[Question] Will Mercure be a hard requirement or an optional (but recommended) feature

### ISSUE THREAD

**Issue by youwe-petervanderwal** [pimcore/studio-backend-bundle#524]
Hi Pimcore,

To prepare (and prioritize) our hosting department ahead of time

Based on

https://github.com/pimcore/studio-backend-bundle/blob/1.x/doc/00_Installation.md#mercure
> The Studio Backend Bundle uses Mercure to push updates to the frontend. **To enable Mercure**, you need to set up a Mercure hub and configure the bundle to use it.

it's not really clear whether Mercure will be a hard requirement to run the new Studio UI or that it is an optional (but recommended) feature.

Can you give some clarity about that?

**Comment by alexz707** [comment]
Hello Peter,

sorry for the late reply!
Concerning your question - yes Mercure is indeed a hard requirement for running the new Studio UI.
Mercure is essential because it enables real-time updates by pushing changes directly to the frontend.

Additionally, we want to handle long-running processes asynchronously. Mercure allows us to push updates about these processes as they complete, rather than requiring the frontend to continually poll the backend.

This setup ensures a better performance and a more responsive user experience.

Best regards,
Alex

**Comment by youwe-petervanderwal** [comment]
Hi @alexz707 

Thanks for the explanation, much appreciated! 
I'll close this issue as it was mainly a question.

Ps. suggestion to add a "Requirements" section to the README.md

**Comment by alexz707** [comment]
HI @youwe-petervanderwal 
thanks for the suggestion we will add it and link it somewho also to the studio UI bundle so it's clear for everyone.
